# Generated by Django 4.1.7 on 2023-02-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemaadmin',
            options={'verbose_name': 'CinemaAdmin', 'verbose_name_plural': 'CinemaAdmins'},
        ),
        migrations.AlterModelOptions(
            name='cinemagoer',
            options={'verbose_name': 'CinemaGoer', 'verbose_name_plural': 'CinemaGoers'},
        ),
    ]
