# Generated by Django 4.1.7 on 2023-02-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cinemagoeradd_delete_cinemagoer_cinemagoer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemagoeradd',
            name='user',
        ),
    ]
