# Generated by Django 4.1.7 on 2023-02-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('imdb_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(blank=True, max_length=255, null=True)),
                ('code_id', models.IntegerField(blank=True, null=True)),
                ('imdb_code', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('runtime', models.SmallIntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('description_intro', models.TextField(blank=True, null=True)),
                ('description_full', models.TextField(blank=True, null=True)),
                ('mpa_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('date_uploaded', models.DateTimeField(blank=True, null=True)),
                ('small_cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('medium_cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_screenshot_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_screenshot_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_screenshot_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('actors', models.ManyToManyField(default='John', through='cinema.Character', to='cinema.actor')),
                ('genres', models.ManyToManyField(default='no info', to='cinema.genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.language')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='genres',
            field=models.ManyToManyField(default='no info', to='cinema.genre'),
        ),
    ]
